# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from formulas import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 450)
        MainWindow.setMinimumSize(QtCore.QSize(450, 450))
        MainWindow.setMaximumSize(QtCore.QSize(450, 450))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 450, 450))
        self.tabWidget.setMinimumSize(QtCore.QSize(450, 450))
        self.tabWidget.setMaximumSize(QtCore.QSize(450, 430))
        self.tabWidget.setObjectName("tabWidget")
        self.add_tab = QtWidgets.QWidget()
        self.add_tab.setObjectName("add_tab")
        self.instr_label = QtWidgets.QLabel(self.add_tab)
        self.instr_label.setGeometry(QtCore.QRect(10, 20, 221, 16))
        self.instr_label.setObjectName("instr_label")
        self.add_output_label = QtWidgets.QLabel(self.add_tab)
        self.add_output_label.setGeometry(QtCore.QRect(10, 130, 341, 20))
        self.add_output_label.setObjectName("add_output_label")
        self.add_input = QtWidgets.QLineEdit(self.add_tab)             #add function input
        self.add_input.setGeometry(QtCore.QRect(90, 60, 113, 20))
        self.add_input.setObjectName("add_input")

        self.input_format_label_1 = QtWidgets.QLabel(self.add_tab)
        self.input_format_label_1.setGeometry(QtCore.QRect(10, 35, 341, 20))
        self.input_format_label_1.setObjectName("input_format_label")

        self.label_3 = QtWidgets.QLabel(self.add_tab)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.label_3.setObjectName("label_3")
        self.add_button = QtWidgets.QPushButton(self.add_tab)
        self.add_button.setGeometry(QtCore.QRect(90, 100, 75, 23))
        self.add_button.setObjectName("add_button")
        self.tabWidget.addTab(self.add_tab, "")



        self.sub_tab = QtWidgets.QWidget()
        self.sub_tab.setObjectName("sub_tab")
        self.label_4 = QtWidgets.QLabel(self.sub_tab)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 221, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.sub_tab)
        self.label_5.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.label_5.setObjectName("label_5")
        self.sub_input1 = QtWidgets.QLineEdit(self.sub_tab)                  #sub function input 1
        self.sub_input1.setGeometry(QtCore.QRect(110, 50, 113, 20))
        self.sub_input1.setObjectName("sub_input1")                          #sub function input 2
        self.sub_input2 = QtWidgets.QLineEdit(self.sub_tab)
        self.sub_input2.setGeometry(QtCore.QRect(110, 100, 113, 20))
        self.sub_input2.setObjectName("sub_input2")
        self.label_6 = QtWidgets.QLabel(self.sub_tab)
        self.label_6.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_6.setObjectName("label_6")
        self.sub_button = QtWidgets.QPushButton(self.sub_tab)
        self.sub_button.setGeometry(QtCore.QRect(110, 140, 75, 23))
        self.sub_button.setObjectName("sub_button")
        self.sub_output_label = QtWidgets.QLabel(self.sub_tab)
        self.sub_output_label.setGeometry(QtCore.QRect(10, 200, 351, 20))
        self.sub_output_label.setObjectName("sub_output_label")
        self.tabWidget.addTab(self.sub_tab, "")


        self.mult_tab = QtWidgets.QWidget()
        self.mult_tab.setObjectName("mult_tab")
        self.label_9 = QtWidgets.QLabel(self.mult_tab)
        self.label_9.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_9.setObjectName("label_9")
        self.instr_label_2 = QtWidgets.QLabel(self.mult_tab)
        self.instr_label_2.setGeometry(QtCore.QRect(10, 20, 221, 21))
        self.instr_label_2.setObjectName("instr_label_2")
        self.mult_input = QtWidgets.QLineEdit(self.mult_tab)                   # mult function input
        self.mult_input.setGeometry(QtCore.QRect(80, 80, 241, 20))
        self.mult_input.setObjectName("mult_input")

        self.input_format_label_2 = QtWidgets.QLabel(self.mult_tab)
        self.input_format_label_2.setGeometry(QtCore.QRect(10, 50, 251, 16))
        self.input_format_label_2.setObjectName("input_format_label")

        self.mult_output_label = QtWidgets.QLabel(self.mult_tab)
        self.mult_output_label.setGeometry(QtCore.QRect(10, 140, 400, 31))
        self.mult_output_label.setObjectName("mult_output_label")
        self.mult_button = QtWidgets.QPushButton(self.mult_tab)
        self.mult_button.setGeometry(QtCore.QRect(80, 110, 75, 23))
        self.mult_button.setObjectName("mult_button")
        self.tabWidget.addTab(self.mult_tab, "")


        self.div_tab = QtWidgets.QWidget()
        self.div_tab.setObjectName("div_tab")
        self.label_13 = QtWidgets.QLabel(self.div_tab)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.div_tab)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 71, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.div_tab)
        self.label_15.setGeometry(QtCore.QRect(10, 20, 221, 16))
        self.label_15.setObjectName("label_15")
        self.div_input1 = QtWidgets.QLineEdit(self.div_tab)                # div function input 1
        self.div_input1.setGeometry(QtCore.QRect(90, 50, 113, 20))
        self.div_input1.setObjectName("div_input1")
        self.div_input2 = QtWidgets.QLineEdit(self.div_tab)           # div function input 2
        self.div_input2.setGeometry(QtCore.QRect(90, 80, 113, 20))
        self.div_input2.setObjectName("div_input2")
        self.div_button = QtWidgets.QPushButton(self.div_tab)
        self.div_button.setGeometry(QtCore.QRect(90, 110, 75, 23))
        self.div_button.setObjectName("div_button")
        self.div_output_label = QtWidgets.QLabel(self.div_tab)
        self.div_output_label.setGeometry(QtCore.QRect(10, 150, 311, 31))
        self.div_output_label.setObjectName("div_output_label")
        self.tabWidget.addTab(self.div_tab, "")
        
        
        self.percent_tab = QtWidgets.QWidget()
        self.percent_tab.setObjectName("percent_tab")
        self.label_16 = QtWidgets.QLabel(self.percent_tab)
        self.label_16.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.percent_tab)
        self.label_17.setGeometry(QtCore.QRect(10, 70, 61, 16))
        self.label_17.setObjectName("label_17")
        self.perc_button = QtWidgets.QPushButton(self.percent_tab)
        self.perc_button.setGeometry(QtCore.QRect(80, 100, 75, 23))
        self.perc_button.setObjectName("perc_button")
        self.perc_input1 = QtWidgets.QLineEdit(self.percent_tab)
        self.perc_input1.setGeometry(QtCore.QRect(80, 30, 231, 20))
        self.perc_input1.setObjectName("perc_input1")
        self.perc_input2 = QtWidgets.QLineEdit(self.percent_tab)
        self.perc_input2.setGeometry(QtCore.QRect(80, 70, 231, 20))
        self.perc_input2.setObjectName("perc_input2")
        self.perc_output_label = QtWidgets.QLabel(self.percent_tab)
        self.perc_output_label.setGeometry(QtCore.QRect(10, 150, 271, 21))
        self.perc_output_label.setObjectName("perc_output_label")
        self.tabWidget.addTab(self.percent_tab, "")

        
        self.widget = QtWidgets.QWidget()                           #History Table Widget
        self.widget.setObjectName("widget")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 401, 341))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 47, 14))
        self.label_19.setObjectName("label_19")
        self.tabWidget.addTab(self.widget, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.instr_label.setText(_translate("MainWindow", "Please Enter Values Separted by a Comma."))
        self.input_format_label_1.setText(_translate("MainWindow", "Input Format: 1, 2, 3, ...etc."))
        self.add_output_label.setText(_translate("MainWindow", "Lable Output"))
        self.label_3.setText(_translate("MainWindow", "Input Values:"))
        self.add_button.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.add_tab), _translate("MainWindow", "Addition"))
        self.label_4.setText(_translate("MainWindow", " Format: Value 1 - Value 2"))
        self.label_5.setText(_translate("MainWindow", "Enter Value 1:"))
        self.label_6.setText(_translate("MainWindow", "Enter Value 2:"))
        self.sub_button.setText(_translate("MainWindow", "Calculate"))
        self.sub_output_label.setText(_translate("MainWindow", "Lable Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sub_tab), _translate("MainWindow", "Subtraction"))
        self.label_9.setText(_translate("MainWindow", "Enter Values:"))
        self.instr_label_2.setText(_translate("MainWindow", "Please Enter Values Separted by a Comma."))
        self.input_format_label_2.setText(_translate("MainWindow", "Input Format: 1, 2, 3, ...etc."))
        self.mult_output_label.setText(_translate("MainWindow", "Lable Output:"))
        self.mult_button.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mult_tab), _translate("MainWindow", "Multiplication"))
        self.label_13.setText(_translate("MainWindow", "Enter Value 1:"))
        self.label_14.setText(_translate("MainWindow", "Enter Value 2:"))
        self.label_15.setText(_translate("MainWindow", " Format: Value 1 / Value 2"))
        self.div_button.setText(_translate("MainWindow", "Calculate"))
        self.div_output_label.setText(_translate("MainWindow", "Label_Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.div_tab), _translate("MainWindow", "Division"))
        self.label_16.setText(_translate("MainWindow", "Enter Value: "))
        self.label_17.setText(_translate("MainWindow", "Percentage:"))
        self.perc_button.setText(_translate("MainWindow", "Calculate"))
        self.perc_output_label.setText(_translate("MainWindow", "Lable Output"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.percent_tab), _translate("MainWindow", "Percentage"))
        self.label_19.setText(_translate("MainWindow", "History"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("MainWindow", "History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
